/**
 * Waypoint JSON Schema — v1
 *
 * Auto-sufficient tree definition generated by @waypointjs/builder.
 * Versioned to allow non-breaking evolution.
 */

// ---------------------------------------------------------------------------
// Operators
// ---------------------------------------------------------------------------

export type ConditionOperator =
  | "equals"
  | "notEquals"
  | "greaterThan"
  | "greaterThanOrEqual"
  | "lessThan"
  | "lessThanOrEqual"
  | "contains"
  | "notContains"
  | "in"
  | "notIn"
  | "exists"
  | "notExists"
  | "matches" // regex
  | "inEnum"
  | "notInEnum";

// ---------------------------------------------------------------------------
// Conditions
// ---------------------------------------------------------------------------

/**
 * A single condition rule.
 * `field` is a dot-path: "stepId.fieldId" for journey data, or "$ext.varId" for external variables.
 */
export interface ConditionRule {
  field: string;
  operator: ConditionOperator;
  value?: unknown;
}

/**
 * A condition group — rules combined with AND or OR.
 * Rules within a group are combined with `combinator`.
 * Groups can be nested via `groups`.
 */
export interface ConditionGroup {
  combinator: "and" | "or";
  rules: ConditionRule[];
  groups?: ConditionGroup[];
}

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

export type ValidationRuleType =
  | "required"
  | "min"
  | "max"
  | "minLength"
  | "maxLength"
  | "email"
  | "url"
  | "regex"
  | "custom"
  // Value comparators
  | "equals"
  | "notEquals"
  | "greaterThan"
  | "greaterThanOrEqual"
  | "lessThan"
  | "lessThanOrEqual"
  | "contains"
  | "notContains"
  | "matches"
  | "inEnum"
  | "notInEnum";

export interface ValidationRule {
  type: ValidationRuleType;
  /** Value for min/max/minLength/maxLength/regex rules */
  value?: string | number;
  /** Error message shown to the user */
  message: string;
  /** For "custom" type: identifier of the validator function registered at runtime */
  customValidatorId?: string;
}

// ---------------------------------------------------------------------------
// Field types
// ---------------------------------------------------------------------------

export type BuiltinFieldType =
  | "text"
  | "number"
  | "email"
  | "password"
  | "tel"
  | "url"
  | "textarea"
  | "select"
  | "multiselect"
  | "checkbox"
  | "radio"
  | "date"
  | "file";

/** Field type — either a builtin or a custom type id registered at runtime */
export type FieldType = BuiltinFieldType | (string & {});

// ---------------------------------------------------------------------------
// Select option
// ---------------------------------------------------------------------------

export interface SelectOption {
  label: string;
  value: string | number;
}

// ---------------------------------------------------------------------------
// Field definition
// ---------------------------------------------------------------------------

export interface FieldDefinition {
  id: string;
  type: FieldType;
  label: string;
  placeholder?: string;
  defaultValue?: unknown;
  /** Options for select/multiselect/radio fields (hardcoded) */
  options?: SelectOption[];
  /** Reference to an external enum — options resolved at runtime from app-provided enums */
  externalEnumId?: string;
  validation?: ValidationRule[];
  /** Controls visibility of this field within its step */
  visibleWhen?: ConditionGroup;
  /** Data dependencies: fields/variables that must have a value before this field is accessible */
  dependsOn?: string[]; // dot-paths "stepId.fieldId" or "$ext.varId"
}

// ---------------------------------------------------------------------------
// Step definition
// ---------------------------------------------------------------------------

export interface StepDefinition {
  id: string;
  title: string;
  /** URL pattern for this step — supports {{PARAM}} placeholders */
  url: string;
  fields: FieldDefinition[];
  /** Controls visibility/insertion of this step in the resolved tree */
  visibleWhen?: ConditionGroup;
  /** Whether this step can be used as a resume point */
  enableResumeFromHere?: boolean;
}

// ---------------------------------------------------------------------------
// External variables
// ---------------------------------------------------------------------------

export interface ExternalVariable {
  id: string;
  label: string;
  /** JavaScript type hint */
  type: "string" | "number" | "boolean" | "object";
  /** If true, Waypoint will throw at runtime if this variable is missing before it is needed */
  blocking: boolean;
  /** Steps / fields that depend on this variable — informational, used by the builder */
  usedIn?: Array<{ stepId: string; fieldId?: string }>;
}

// ---------------------------------------------------------------------------
// External enums (app-provided option lists)
// ---------------------------------------------------------------------------

/**
 * An externally-provided list of options for select/multiselect/radio fields.
 * The actual values are injected at runtime (builder prop / runner prop) so
 * the schema only stores a reference (`externalEnumId`).
 */
export interface ExternalEnum {
  id: string;
  label: string;
  values: SelectOption[];
}

// ---------------------------------------------------------------------------
// Custom field types
// ---------------------------------------------------------------------------

/**
 * A custom field type registered in the builder.
 * `metadata` is passed through as-is so the backend can enrich it.
 */
export interface CustomTypeDefinition {
  id: string;
  label: string;
  /** Icon name or URL — used by the builder UI */
  icon?: string;
  /** Default validation rules applied when this type is used */
  defaultValidation?: ValidationRule[];
  /** Arbitrary metadata — enrichable by the backend */
  metadata?: Record<string, unknown>;
}

// ---------------------------------------------------------------------------
// Persistence mode
// ---------------------------------------------------------------------------

export type PersistenceMode =
  | "zustand"        // local Zustand store with persist middleware
  | "backend-step"   // save to backend after each step
  | "backend-manual" // dev controls when to save via onStepSubmit hook

// ---------------------------------------------------------------------------
// Root schema
// ---------------------------------------------------------------------------

export interface WaypointSchema {
  /** Schema version — increment on breaking changes */
  version: "1";
  /** Unique identifier for this journey definition */
  id: string;
  /** Human-readable name */
  name: string;
  /** Ordered list of steps — order reflects default display order */
  steps: StepDefinition[];
  /** External variables this journey depends on */
  externalVariables?: ExternalVariable[];
  /** Custom field types registered for this journey */
  customTypes?: CustomTypeDefinition[];
  /** Default persistence mode */
  persistenceMode?: PersistenceMode;
  /** Arbitrary metadata */
  metadata?: Record<string, unknown>;
}
